#!/usr/bin/env bash
set -ex

HERE=$(dirname $0)
. $HERE/common

# This script does a very basic test of the proxy image by running it up and checking nginx is running
docker run -d \
  --name daedalus-proxy \
  $TAG_SHA \
  localhost daedalus-proxy http://daedalus-web-app:3000

docker exec daedalus-proxy /usr/local/bin/build-self-signed-certificate /run/proxy GB London IC jameel-institute localhost

sleep 1
docker logs daedalus-proxy | 2>&1 grep "Certificate files detected. Running nginx" || (echo "Expected output not found"; exit 1)
echo "Expected output was found"