docker:
  network: daedalus
  prefix: daedalus
proxy:
  image:
    repo: ghcr.io/jameel-institute
    name: daedalus-proxy
    tag: main
  port_http: 80
  port_https: 443
  logs_location: /var/log/nginx
redis:
  image:
    repo: library
    name: redis
    tag: latest
api:
  image:
    repo: mrcide
    name: daedalus.api
    tag: latest
  port: 8001
  queue_id: daedalus-queue
  number_of_workers: 1
web_app_db:
  image:
    repo: ghcr.io/jameel-institute
    name: daedalus-web-app-db
    tag: main
  port: 5432
  data_location: /pgdata
  postgres:
    user: daedalus-web-app-user
web_app:
  image:
    repo: ghcr.io/jameel-institute
    name: daedalus-web-app
    tag: main
  port: 3000
acme_buddy:
  image:
    repo: ghcr.io/reside-ic
    name: acme-buddy
    tag: main
    hdb_username: VAULT:secret/certbot-hdb/credentials:username
    hdb_password: VAULT:secret/certbot-hdb/credentials:password
  port: 2112
