docker:
  network: daedalus
  prefix: daedalus
proxy:
  image:
    repo: ghcr.io/jameel-institute
    name: daedalus-proxy
    tag: main
  port_http: 80
  port_https: 443
  logs_location: /var/log/nginx
api:
  image:
    repo: mrcide
    name: daedalus.api
    tag: latest
  port: 8001
web_app_db:
  image:
    repo: ghcr.io/jameel-institute
    name: daedalus-web-app-db
    tag: main
  port: 5432
  data_location: /pgdata
  postgres:
    user: daedalus-web-app-user
web_app:
  image:
    repo: ghcr.io/jameel-institute
    name: daedalus-web-app
    tag: main
  port: 3000