proxy:
  host: daedalus.jameel-institute.org
api:
  number_of_workers: 4
web_app_db:
  postgres:
    user: VAULT:secret/daedalus/postgres/dev:user
    password: VAULT:secret/daedalus/postgres/dev:password
vault:
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    method: github
