proxy:
  image:
    repo: ghcr.io/jameel-institute
    name: daedalus-proxy
    # TODO: update to main when merged
    tag: jidea-50
  host: beebop-dev.dide.ic.ac.uk
  ssl:
    certificate: VAULT:secret/daedalus/ssl/staging:cert
    key: VAULT:secret/beebop/daedalus/ssl/staging:key