proxy:
  host: daedalus-dev.dide.ic.ac.uk
web_app_db:
  postgres:
    user: VAULT:secret/daedalus/postgres/dev:user
    password: VAULT:secret/daedalus/postgres/dev:password
vault:
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    method: github
acme_buddy:
  image:
    repo: ghcr.io/reside-ic
    name: acme-buddy
    tag: main
  hdb_username: VAULT:secret/certbot-hdb/credentials:username
  hdb_password: VAULT:secret/certbot-hdb/credentials:password
  port: 2112
