proxy:
  ssl:
    certificate: VAULT:secret/daedalus/ssl/staging:cert
    key: VAULT:secret/daedalus/daedalus/ssl/staging:key
vault:
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    method: github