on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
name: Build proxy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build proxy
        run: ./proxy/build
      - name: Push SHA
        run: ./proxy/push
      - name: Push branch tag
        run: ./proxy/push-branch-tag
